### ISSUE TITLE
Getting error while running the make command 

### ISSUE THREAD

**Issue by Saurabh-704** [orafce/orafce#110]
Hello All!!
I am getting error while running the make command.
**Error** - file.c:22:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
                                 ^
compilation terminated.
make: *** [file.o] Error 1

Link which followed to install - https://info.crunchydata.com/blog/migrating-from-oracle-to-postgresql-questions-and-considerations#:~:text=Orafce%20is%20a%20useful%20extension,.com%2Forafce%2Forafce.

Postgresql version -  PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

Can anyone please help me with this issue?!
Thanks in advance!

**Comment by okbob** [comment]
út 21. 7. 2020 v 5:54 odesílatel saurabh Gupta <notifications@github.com>
napsal:

> Hello All!!
> I am getting error while running the make command.
> *Error* - file.c:22:33: fatal error: access/htup_details.h: No such file
> or directory
> #include "access/htup_details.h"
> ^
> compilation terminated.
> make: *** [file.o] Error 1
>
> Link which followed to install -
> https://info.crunchydata.com/blog/migrating-from-oracle-to-postgresql-questions-and-considerations#:~:text=Orafce%20is%20a%20useful%20extension,.com%2Forafce%2Forafce
> .
>
> Postgresql version - PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by
> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
>
Can anyone please help me with this issue?!
> Thanks in advance!
>
first you have to check a prerequisites:

postgresql-server-dev package - attention ensure same version of Postgres
and same repository like your Postgres server version

I checked my Postgres source and the header file "htup_details.h" really
exists in "access" directory. So orafce is correct.

Some people have a problem because they mix Postgres packages from
different repositories, or mix different versions of Postgres on one
server. It is possible, but then you have to be sure of the correct setting
of PATH env.

So please, check if your include directory with Postgres subdir is related
to Postgres version that is used for compilation of orafce. Now, it looks
so your build environment is broken.

[pavel@nemesis ~]$ pg_config
BINDIR = /usr/local/pgsql/bin
DOCDIR = /usr/local/pgsql/share/doc
HTMLDIR = /usr/local/pgsql/share/doc
INCLUDEDIR = /usr/local/pgsql/include
PKGINCLUDEDIR = /usr/local/pgsql/include
INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
LIBDIR = /usr/local/pgsql/lib
PKGLIBDIR = /usr/local/pgsql/lib
LOCALEDIR = /usr/local/pgsql/share/locale
MANDIR = /usr/local/pgsql/share/man
SHAREDIR = /usr/local/pgsql/share
SYSCONFDIR = /usr/local/pgsql/etc
PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--enable-tap-tests' '--enable-debug' 'CFLAGS=-Wall
-Wmissing-prototypes -Wdeclaration-after-statement  -Wendif-labels
-Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv
-fexcess-precision=standard -g -O2 -Werror=switch' '--with-libxml'
'--with-python' '--enable-cassert'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith
-Wdeclaration-after-statement -Werror=vla -Wendif-labels
-Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type
-Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
-Wno-format-truncation -Wno-stringop-truncation -g -Wall
-Wmissing-prototypes -Wdeclaration-after-statement  -Wendif-labels
-Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv
-fexcess-precision=standard -g -O2 -Werror=switch
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed
-Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxml2 -lz -lreadline -lrt -ldl -lm
VERSION = PostgreSQL 14devel

check INCLUDEDIR-SERVER = /usr/local/pgsql/include/server (the value can be
different on different systems)

in this directory should be file pg_config.h. The content should be like:


#define PG_VERSION_NUM 140000

/* A string containing the version number, platform, and C compiler */
#define PG_VERSION_STR "PostgreSQL 14devel on x86_64-pc-linux-gnu, compiled
by gcc (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1), 64-bit"

I have Postgres 14. If you have Postgres 12, then it will be modified for
Postgres 12.

Regards

Pavel

**Comment by Saurabh-704** [comment]
Hello @okbob ,Thank you for your response.
I have gone to path - /usr/include/pgsql/server/access, and checked the "htup_details.h" file, but I didnt found the file there.
So am I looking in wrong path or something I have did wrong?!
Can you help me with this?!

**Comment by okbob** [comment]
út 21. 7. 2020 v 10:44 odesílatel saurabh Gupta <notifications@github.com>
napsal:

> Hello @okbob <https://github.com/okbob> ,Thank you for your response.
> I have gone to path - /usr/include/pgsql/server/access, and checked the
> "htup_details.h" file, but I didnt found the file there.
> So am I looking in wrong path or something I have did wrong?!
> Can you help me with this?!
>

what is in  pg_config.h?

**Comment by Saurabh-704** [comment]
This is what I have in my pg_config.h file 

/*
 * Kluge to support multilib installation of both 32- and 64-bit RPMS:
 * we need to arrange that header files that appear in both RPMs are
 * identical.  Hence, this file is architecture-independent and calls
 * in an arch-dependent file that will appear in just one RPM.
 *
 * To avoid breaking arches not explicitly supported by Red Hat, we
 * use this indirection file *only* on known multilib arches.
 *
 * Note: this may well fail if user tries to use gcc's -I- option.
 * But that option is deprecated anyway.
 */
#if defined(__x86_64__)
#include "pg_config_x86_64.h"
#elif defined(__i386__)
#include "pg_config_i386.h"
#elif defined(__ppc64__) || defined(__powerpc64__)
#include "pg_config_ppc64.h"
#elif defined(__ppc__) || defined(__powerpc__)
#include "pg_config_ppc.h"
#elif defined(__s390x__)
#include "pg_config_s390x.h"
#elif defined(__s390__)
#include "pg_config_s390.h"
#elif defined(__sparc__) && defined(__arch64__)
#include "pg_config_sparc64.h"
#elif defined(__sparc__)
#include "pg_config_sparc.h"
#endif

**Comment by okbob** [comment]
út 21. 7. 2020 v 12:12 odesílatel saurabh Gupta <notifications@github.com>
napsal:

> This is what I have in my pg_config.h file
>

it looks strange. It should be in directory "server" and there should be
line with constant

#define PG_VERSION_NUM

Pavel

/*

**Comment by Saurabh-704** [comment]
ok @okbob . So now what should I do?
Can you suggest me something else that can work for me?

**Comment by Saurabh-704** [comment]
postgresql.x86_64                      9.2.24-4.el7_8              @ol7_latest
postgresql-devel.x86_64                9.2.24-4.el7_8              @ol7_latest
postgresql-docs.x86_64                 9.2.24-4.el7_8              @ol7_latest
postgresql-libs.x86_64                 9.2.24-4.el7_8              @ol7_latest
postgresql-server.x86_64               9.2.24-4.el7_8              @ol7_latest
postgresql12.x86_64                    12.3-5PGDG.rhel7            @pgdg12
postgresql12-devel.x86_64              12.3-5PGDG.rhel7            @pgdg12
postgresql12-libs.x86_64               12.3-5PGDG.rhel7            @pgdg12
postgresql12-server.x86_64             12.3-5PGDG.rhel7            @pgdg12
spacewalk-postgresql-clean.noarch      2.7.4-1.0.1.el7             @ol7_spacewalk27_server

This is the result of - yum list installed | grep postgres @okbob

**Comment by okbob** [comment]
út 21. 7. 2020 v 13:36 odesílatel saurabh Gupta <notifications@github.com>
napsal:

> postgresql.x86_64 9.2.24-4.el7_8 @ol7_latest
> postgresql-devel.x86_64 9.2.24-4.el7_8 @ol7_latest
> postgresql-docs.x86_64 9.2.24-4.el7_8 @ol7_latest
> postgresql-libs.x86_64 9.2.24-4.el7_8 @ol7_latest
> postgresql-server.x86_64 9.2.24-4.el7_8 @ol7_latest
> postgresql12.x86_64 12.3-5PGDG.rhel7 @pgdg12
> postgresql12-devel.x86_64 12.3-5PGDG.rhel7 @pgdg12
> postgresql12-libs.x86_64 12.3-5PGDG.rhel7 @pgdg12
> postgresql12-server.x86_64 12.3-5PGDG.rhel7 @pgdg12
> spacewalk-postgresql-clean.noarch 2.7.4-1.0.1.el7 @ol7_spacewalk27_server
>
> This is the result of - yum list installed | grep postgres @okbob
> <https://github.com/okbob>
>
you have necessary packages, but maybe you have to wrong setting of PATH
environment.

The package postgresql12-devel should contain a pg_config application. You
should set PATH to be executed by default this instance of pg_config.

It is a little bit unhappy using Postgres from two sources - you have RH
packages, and PGDG too. Probably header files, that you found, are related
to Postgres 9.2.

Recheck env PATH and pg_config application, maybe you have chaos on your
libraries and you should to clean it first or reinstall

**Comment by Saurabh-704** [comment]
Ok @okbob . So what you mean to say is to remove the postgresql and reinstall it right?

**Comment by okbob** [comment]
út 21. 7. 2020 v 14:08 odesílatel saurabh Gupta <notifications@github.com>
napsal:

> Ok @okbob <https://github.com/okbob> . So what you mean to say is to
> remove the postgresql and reinstall it right?
>
you need Postgres just from one repository. You should to remove all
Postgres server related packages from RH repositories
