### ISSUE TITLE
Installing orafce on EDB 12.4

### ISSUE THREAD

**Issue by 0xmang** [orafce/orafce#117]
Hi,

Is it possible to install orafce on EDB 12.4 (in standard mode) ? 
if yes, which orafce version is the right one?

Thanks!

**Comment by luss** [comment]
EnterpriseDB includes most of the equivalent of Orafce as part of their
proprietary binaries.   If their is specific orafce functionality that is
missing...  u should talk to the good folks at EDB.

**Comment by okbob** [comment]
pá 9. 10. 2020 v 18:46 odesílatel Denis Lussier <notifications@github.com>
napsal:

> EnterpriseDB includes most of the equivalent of Orafce as part of their
> proprietary binaries. If their is specific orafce functionality that is
> missing... u should talk to the good folks at EDB.
>

yes - if you have EDB with Oracle compatibility support, then installation
of Orafce can be catastrophic (it has not any sense, and probably it can do
a lot of issues).

Regards

Pavel

**Comment by 0xmang** [comment]
@okbob @luss Thank you for your replies, 
what i have is EnterpriseDB but in "postgres mode", so all the oracle-equivalents are not there...
so what i am asking **if Orafce can work on EDB in postgres mode**, not in oracle-compatible mode.

Thanks!

**Comment by okbob** [comment]
pá 9. 10. 2020 v 19:03 odesílatel 0xmang <notifications@github.com> napsal:

> @okbob <https://github.com/okbob> @luss <https://github.com/luss> Thank
> you for your replies,
> what i have is EnterpriseDB but in "postgres mode", so all the
> oracle-equivalents are not there...
> so what i am asking *if Orafce can work on EDB in postgres mode*, not in
> oracle-compatible mode.
>
I am not sure - I expect so EDB in Postgres mode is just Postgres with a
different installer, and then probably you can use Orafce as any other
Postgres extension. BUt I didn't test it.

Against Postgres 12 you can use any Orafce compiled against Postgres 12 and
your operation system (if EDB has not some own hacks)

PostgreSQL extensions are compiled against specific Postgres major release,
against the operating system and against bus width - 32 or 64. Probably you
should compile Orafce by self from source code, because all precompiled
packaged Orafce depends on some community Postgres.

**Comment by luss** [comment]
This is a good question.  Ask EDB support for an accurate answer.  My
suspicion is that they haven't tried it either.   EDB binaries in "postgres
mode" are 99.99% PostgreSQLl and it should (perhaps entirely) work.   The
0.001% stuff that isn't pure PG source code is mostly code hooks so that
their proprietary goodness can run at native speeds.

--Luss
  Founder & Cheie Architect of EDB  2004 - 2009
