### ISSUE TITLE
oracle.sysdate() is not providing the Date as per DB or SERVER timezone

### ISSUE THREAD

**Issue by jagmohankaintura-tl** [orafce/orafce#126]
We made a change in the timezone on the database from UTC to Asia/HongKong by modiifying the  timezone parameter in postgresql.conf and restarted the Cluster.  Inbuilt date functions of PostgreSQL are reflecting the dates as per new timezone, but oralce.sysdate() continue to reflect date for UTC timezone only.

DB server TImeZone :
[postgres@SAZCPOC001DB ~]$ date
Thu Jan  7 10:04:43 HKT 2021

Inside the Database :  sysdate is not showing proper date as per TimeZone
zdcq12c2=# select now(),current_timestamp,clock_timestamp(),oracle.sysdate();
              now              |       current_timestamp       |        clock_timestamp        |       sysdate
-------------------------------+-------------------------------+-------------------------------+---------------------
 2021-01-07 10:03:52.324022+08 | 2021-01-07 10:03:52.324022+08 | 2021-01-07 **10**:03:52.324396+08 | 2021-01-07 **02:**03:52

zdcq12c2=# show timezone;
    TimeZone
----------------
 Asia/Hong_Kong
(1 row)

zdcq12c2=# show orafce.timezone;
 orafce.timezone
-----------------
 Asia/Hong_Kong
(1 row)

This functions Continues to Display GMT only irrespective of any change in TImezone at Server or DB level.
zdcq12c2=# select oracle.dbtimezone();
 dbtimezone
------------
 GMT
(1 row)

Right now we cant DROP and CREATE the orafce extension as it have thousands decencies over source code. 
Can team guide what more we have to do in order to modify the sysdate to reflect the date as per database.

**Comment by okbob** [comment]
Hi

čt 7. 1. 2021 v 3:13 odesílatel jagmohankaintura-tl <
notifications@github.com> napsal:

> We made a change in the timezone on the database from UTC to Asia/HongKong
> by modiifying the timezone parameter in postgresql.conf and restarted the
> Cluster. Inbuilt date functions of PostgreSQL are reflecting the dates as
> per new timezone, but oralce.sysdate() continue to reflect date for UTC
> timezone only.
>
> DB server TImeZone :
> [postgres@SAZCPOC001DB ~]$ date
> Thu Jan 7 10:04:43 HKT 2021
>
> Inside the Database : sysdate is not showing proper date as per TimeZone
> zdcq12c2=# select
> now(),current_timestamp,clock_timestamp(),oracle.sysdate();
> now | current_timestamp | clock_timestamp | sysdate
>
> -------------------------------+-------------------------------+-------------------------------+---------------------
> 2021-01-07 10:03:52.324022+08 | 2021-01-07 10:03:52.324022+08 | 2021-01-07
> *10*:03:52.324396+08 | 2021-01-07 **02:**03:52
> zdcq12c2=# show timezone;
> TimeZone
>
> Asia/Hong_Kong
> (1 row)
> zdcq12c2=# show orafce.timezone;
> orafce.timezone
>
> Asia/Hong_Kong
> (1 row)
> This functions Continues to Display GMT only irrespective of any change in
> TImezone at Server or DB level.
> zdcq12c2=# select oracle.dbtimezone();
> dbtimezone
>
> GMT
> (1 row)
>
> Right now we cant DROP and CREATE the orafce extension as it have
> thousands decencies over source code.
> Can team guide what more we have to do in order to modify the sysdate to
> reflect the date as per database.
>
I found a one bug - orafce.timezone displays current time zone instead of
orafce.timezone. But when I set this value, then I got correct result of
oracle.sysdate()

postgres=# select now(), now() at time zone 'Asia/Hong_Kong',
oracle.sysdate();
┌───────────────────────────────┬────────────────────────────┬─────────────────────┐
│              now              │          timezone          │
sysdate       │
╞═══════════════════════════════╪════════════════════════════╪═════════════════════╡
│ 2021-01-07 18:29:32.354986+01 │ 2021-01-08 01:29:32.354986 │ 2021-01-07
17:29:32 │
└───────────────────────────────┴────────────────────────────┴─────────────────────┘
(1 row)

postgres=# set orafce.timezone to 'Asia/Hong_Kong';
SET
postgres=# select oracle.sysdate();
┌─────────────────────┐
│       sysdate       │
╞═════════════════════╡
│ 2021-01-08 01:29:53 │
└─────────────────────┘
(1 row)

postgres=# select oracle.dbtimezone();
┌────────────────┐
│   dbtimezone   │
╞════════════════╡
│ Asia/Hong_Kong │
└────────────────┘
(1 row)

Probably you didn't set correctly (permanently) orafce.timezone. There was
a bug and "show orafce.timezone" displays the value of "timezone". The
result of oracle.dbtimezone() is important and it shows so you didn't
change it.

If you want to do persistent change, then write in postgresql.conf

orafce.timezone = 'Asia/Hong_Kong'

and make reload

select oracle.dbtimezone() must to show 'Asia/Hong_Kong'

or ALTER DATABASE xxx SET orafce.timezone = 'Asia/Hong_Kong';

and reload

You don't need to reinstall orafce. Just you need to correctly and
persistently set the value of orafce.timezone(). I checked this
functionality and it is working. Check result of oracle.dbtimezone. Only
output of this function is true.

**Comment by okbob** [comment]
https://github.com/orafce/orafce/commit/93ad320a78a2da042dcb80d280ae2992dbeb42d5

**Comment by jagmohankaintura-tl** [comment]
Thank you. It worked after placing orafce.timezone in postgresql.conf.

**Comment by okbob** [comment]
Thank you for bugreport
