### ISSUE TITLE
Make decode more compatible with oracle

### ISSUE THREAD

**Issue by junfx** [orafce/orafce#158]
[1] https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions040.htm

According to [1], Oracle's decode allows to mix numeric and character(s) in `search`/`result`, and implicitly converts  remaining arguments to the type of first `search`/`result`. Also, it accepts any amount of [search, result] pairs.

Have you ever considered declaring `decode` as
```sql
CREATE FUNCTION public.decode("any", "any", numeric) return numeric ...;
CREATE FUNCTION public.decode("any", "any", numeric, variadic "any") return numeric ...;

CREATE FUNCTION public.decode("any", "any", text) return text ...;
CREATE FUNCTION public.decode("any", "any", text, variadic "any") return text ...;

-- similar for type date, time, ...
...
```
and comparing `search` with `expr` in CString format, i.e. ignore their type.

**Comment by okbob** [comment]
pá 3. 12. 2021 v 8:09 odesílatel junfx ***@***.***> napsal:

> [1]
> https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions040.htm
>
> According to [1], Oracle's deocde allows to mix numeric and character(s)
> in search/result, and implicitly converts remaining arguments to the type
> of first search/result. Also, it accepts any amount of [search, result]
> pairs.
>
> Have you ever considered declaring decode as
>
> CREATE FUNCTION public.decode("any", "any", numeric) return numeric ...;CREATE FUNCTION public.decode("any", "any", numeric, variadic "any") return numeric ...;
> -- similar for type text, date, time, ...
> ...
>
> and comparing search with expr in CString format, i.e. ignore their type.
>
Yes, I did it. There are some nice benefits but strong disadvantages too.

+ it can reduce an complexity of decode function in orafce

+ probably this implementation can emulate decode much more close than
current implementation

- unfortunately - the work with "any" type has very negative impacts on
performance - you cannot to store data to plan cache - and you cannot to
move some calculations to planning time

- Comparing cstrings is not too good idea. Few years ago it was removed
from plpgsql and I am very happy about it. There are a lot of problems -
for example, comparing int and numeric 10 = 10.00 will fail. So you need to
do conversion to the most common type, and when you have to do it inside a
function, then there is significant overhead when the function starts.
Sometimes you can store these casts to the inner function cache, but you
have to recheck the validity of this cache every call, and this is slow
again.

If I started Orafce today, maybe I used it - because now variadic "any" can
reduce some work. But now, I don't want to change it. The benefit for usual
cases is not too big, and the negative performance impact can be
significant. Probably, I am able to solve these performance issues for
basic most usual types, but then the code complexity will be not too much
less than current.
