### ISSUE TITLE
Upgrade error: cannot remove dependency on schema pg_catalog because it is a system object

### ISSUE THREAD

**Issue by danielgustafsson** [orafce/orafce#190]
Updating from 3.21 to any later version on Postgres 11 raise an error which I'm not really sure what to do with:
```
db=# alter extension orafce update to '3.22';
ERROR:  cannot remove dependency on schema pg_catalog because it is a system object
```
Running the very first statement from the 3.21--3.22 file manually shows the error:
```
db=# ALTER FUNCTION pg_catalog.trunc(date,text) SET SCHEMA oracle;
ERROR:  cannot remove dependency on schema pg_catalog because it is a system object
```
The actual update was against 3.24.2 but the failure happens in the 3.21--3.22 part, and only on Postgres 11 (the version tested is 11.17), the other supported Postgres versions passed upgrading fine.

**Comment by okbob** [comment]
Hi

pá 19. 8. 2022 v 23:04 odesílatel Daniel Gustafsson <
***@***.***> napsal:

> Updating from 3.21 to any later version on Postgres 11 raise an error
> which I'm not really sure what to do with:
>
> db=# alter extension orafce update to '3.22';
> ERROR:  cannot remove dependency on schema pg_catalog because it is a system object
>
> Running the very first statement from the 3.21--3.22 file manually shows
> the error:
>
> db=# ALTER FUNCTION pg_catalog.trunc(date,text) SET SCHEMA oracle;
> ERROR:  cannot remove dependency on schema pg_catalog because it is a system object
>
> The actual update was against 3.24.2 but the failure happens in the
> 3.21--3.22 part, and only on Postgres 11 (the version tested is 11.17), the
> other supported Postgres versions passed upgrading fine.
>
Unfortunately, it looks like PostgreSQL feature - older releases (<12)
doesn't supports altering objects in system catalogue :-(

(2022-08-20 05:24:31) postgres=# create or replace function
pg_catalog.foo(a int) returns int as $$begin return a + 1; end$$ language
plpgsql;
CREATE FUNCTION
(2022-08-20 05:25:14) postgres=# alter function pg_catalog.foo(a int) set
schema public;
ERROR:  cannot remove dependency on schema pg_catalog because it is a
system object

I fixed update script

please check
https://github.com/orafce/orafce/commit/5c60207cbae6af51adede8e3dbe65863714c5d14

**Comment by danielgustafsson** [comment]
I can confirm that. Re-running the upgrade on a freshly built master works in Postgres 11, thanks for the quick fix. Will this be shipped in a release in the near future?

**Comment by okbob** [comment]
so 20. 8. 2022 v 9:58 odesílatel Daniel Gustafsson ***@***.***>
napsal:

> I can confirm that. Re-running the upgrade on a freshly built master works
> in Postgres 11, thanks for the quick fix. Will this be shipped in a
> patchrelease in the near future?
>
I released it today.

https://github.com/orafce/orafce/releases/tag/VERSION_3_24_3

**Comment by danielgustafsson** [comment]
Great thanks!

**Comment by okbob** [comment]
so 20. 8. 2022 v 12:41 odesílatel Daniel Gustafsson <
***@***.***> napsal:

> Great thanks!
>
thank you for bugreport and test
