### ISSUE TITLE
Error importing DMP with version higher than 3.22

### ISSUE THREAD

**Issue by RomainBZH35** [orafce/orafce#197]
We use Postgresql 11 and orafce 3.9. we export a database to dmp. 
when we import to database postgresql 11 and orafce 3.22 and higher the restore failed.

pg_restore: création de FUNCTION « public.convert(public.varchar2, double precision, public.varchar2) »
pg_restore: [programme d'archivage (db)] Erreur pendant le traitement de la TOC (« PROCESSING TOC ») :
pg_restore: [programme d'archivage (db)] Erreur à partir de l'entrée TOC 1747 ; 1255 3292305 FUNCTION convert(public.varchar2, double precision, public.varchar2) affaire
pg_restore: [programme d'archivage (db)] could not execute query: ERREUR:  le type public.varchar2 n'existe pas

When we import on a database V11 with orafce 3.21 it's OK.

where is the problem ?

**Comment by okbob** [comment]
When you use dump/restore, then you need to use same versions of extensions. In version 3.22 I did massive cleaning and moved all orafce's functions from schema public and pg_catalog to oracle schema. These changes are done by update script orafce--3.21--3.22.sql . But because you didn't executed this script, the database objects are not on correct places.

You need to update to orafce 3.22 first and the dump your database, or use orafce 3.21 on target server, restore data and then upgrade to orafce 3.22

**Comment by RomainBZH35** [comment]
Tks, we will upgrade.
