### ISSUE TITLE
remainder function is not fully compatible with oracle

### ISSUE THREAD

**Issue by winter-loo** [orafce/orafce#225]
For sql,

```sql
select remainder('24.2', 2) from dual;
```

oracle database can give me the answer: 0.2. But orafce reports the error:

```
ERROR:  invalid input syntax for type integer: "24.2"
LINE 1: select remainder('24.2', 2) from dual;
```

**Comment by okbob** [comment]
Hi

pá 28. 7. 2023 v 8:14 odesílatel winter-loo ***@***.***>
napsal:

> For sql,
>
> select remainder('24.2', 2) from dual;
>
> oracle database can give me the answer: 0.2. But orafce reports the error:
>
> ERROR:  invalid input syntax for type integer: "24.2"
> LINE 1: select remainder('24.2', 2) from dual;
>
>
This is expected behaviour. PostgreSQL has a different type system that
distinguishes between integer numeric and other numeric values, and then
full compatibility is not possible.

First value is in your case string literal of unknown type, the second
value is integer, so Postgres will try to convert the first value to
integer, which is impossible.

You should to use explicit type specification

(2023-07-28 08:26:32) postgres=# select oracle.remainder('24.2'::numeric,
2) from oracle.dual;
┌───────────┐
│ remainder │
╞═══════════╡
│       0.2 │
└───────────┘
(1 row)

(2023-07-28 08:26:59) postgres=# select oracle.remainder('24.2',
2::numeric) from oracle.dual;
┌───────────┐
│ remainder │
╞═══════════╡
│       0.2 │
└───────────┘
(1 row)

(2023-07-28 08:27:07) postgres=# select oracle.remainder('24.2', 2.0) from
oracle.dual;
┌───────────┐
│ remainder │
╞═══════════╡
│       0.2 │
└───────────┘
(1 row)

**Comment by okbob** [comment]
should be fixed by 593d33a67a27f67ab4de71b58c982120d27c6a20should be fixed by
