### ISSUE TITLE
fatal error LNK1120: 1 unresolved externals while compiling in Windows.

### ISSUE THREAD

**Issue by yansheng836** [orafce/orafce#291]
like https://github.com/orafce/orafce/issues/156

I follow the [README.msvc](https://github.com/orafce/orafce/blob/master/README.msvc) , on my windows10, but will have some errors.

LNK2001: unresolved external symbol Mode
LNK1120: 1 unresolved externals

![image](https://github.com/user-attachments/assets/5730d18a-2a9f-4484-89f2-68beb2c29ac3)

detail:

```
……
1>varchar2.c
1>F:\Database\PostgreSQL\11\include\server\libpq\pqformat.h(116,10): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>(compiling source file 'varchar2.c')
1>F:\Database\PostgreSQL\11\include\server\libpq\pqformat.h(111,15): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>(compiling source file 'varchar2.c')
1>   Creating library E:\ProgramFiles\Microsoft Visual Studio\vs-project\orafce\x64\Release\orafce.lib and object E:\ProgramFiles\Microsoft Visual Studio\vs-project\orafce\x64\Release\orafce.exp
1>file.obj : error LNK2001: unresolved external symbol Mode
1>E:\ProgramFiles\Microsoft Visual Studio\vs-project\orafce\x64\Release\orafce.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "orafce.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 15:51 and took 17.686 seconds ==========
```

my env:
orafce-4.13.5
window10
db:pg11

**Comment by okbob** [comment]
Hi


čt 21. 11. 2024 v 9:03 odesílatel Yan Sheng ***@***.***>
napsal:

> like #156 <https://github.com/orafce/orafce/issues/156>
>
> I follow the README.msvc
> <https://github.com/orafce/orafce/blob/master/README.msvc> , on my
> windows10, but will has some error.
>
> LNK2001: unresolved external symbol Mode
> LNK1120: 1 unresolved externals
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/5730d18a-2a9f-4484-89f2-68beb2c29ac3>
>
> detail:
>
> ……
> 1>varchar2.c
> 1>F:\Database\PostgreSQL\11\include\server\libpq\pqformat.h(116,10): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
> 1>(compiling source file 'varchar2.c')
> 1>F:\Database\PostgreSQL\11\include\server\libpq\pqformat.h(111,15): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
> 1>(compiling source file 'varchar2.c')
> 1>   Creating library E:\ProgramFiles\Microsoft Visual Studio\vs-project\orafce\x64\Release\orafce.lib and object E:\ProgramFiles\Microsoft Visual Studio\vs-project\orafce\x64\Release\orafce.exp
> 1>file.obj : error LNK2001: unresolved external symbol Mode
> 1>E:\ProgramFiles\Microsoft Visual Studio\vs-project\orafce\x64\Release\orafce.dll : fatal error LNK1120: 1 unresolved externals
> 1>Done building project "orafce.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> ========== Build completed at 15:51 and took 17.686 seconds ==========
>
> my env:
> orafce-4.13.5
> window10
> db:pg11
>

It looks strange - Mode is a symbol from miscadmin.h - Orafce doesn't use
it - but it is defined there

extern ProcessingMode Mode;

#define IsBootstrapProcessingMode() (Mode == BootstrapProcessing)
#define IsInitProcessingMode()<><-->(Mode == InitProcessing)
#define IsNormalProcessingMode()<-->(Mode == NormalProcessing)

If I remember I hadn't problem to build orafce for Postgres 11.
http://okbob.blogspot.com/2019/10/precompiled-libraries-for-orafce-38-for.html

This code in Postgres is unchanged for a lot of years.

I had a problem with dbms_file on mswin, but I was able to compile it.
Please, can you recheck all options of your projects like "compile as C
project"? I am not sure, but I remember very strange problems with linking
when I wrongly set some options. Compilation on mswin is extremely
sensitive to correct project settings. I am sorry I cannot help better,
because I use ms win only a few times per year and msvc only once per year
just for compilation orafce for the last two versions of Postgres, and I am
very unhappy every time.

**Comment by okbob** [comment]
pá 22. 11. 2024 v 7:50 odesílatel Yan Sheng ***@***.***>
napsal:

> I didn't find the Mode keyword in this project, and I don't know the
> source (because I didn't specify which file)...
>
This is part of PostgreSQL - you need to look at PostgreSQL source code.
Unfortunately, MS Win has different methods on how to export some symbols
in dll, so theoretically there can be some issue. PostgreSQL is Linux
native - Orafce too, and build to MS Win (of Orafce) is not often tested.
Although I know some users who do it.


> My compile as:
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/afa53e0c-2cb4-4393-9dbf-82932b8cce72>
>
> My visual studio is 2020 (newest), I'm not sure if it has anything to do
> with the version?
>
I don't know. Probably not. The question is if your build environment is
consistent.


> In fact, after I failed many times; Fortunately, I found your article,
> thank you very much. I finally installed version 11 dll.
> If no one else is having this problem, shut it down.
> @okbob <https://github.com/okbob>
>

ok

PostgreSQL 11 is unsupported release, so you should to migrate to some
supported release - 13 and higher
