### ISSUE TITLE
Bug in to_number 

### ISSUE THREAD

**Issue by dezdechado** [orafce/orafce#47]
Oracle: `select to_number('') from dual` returns NULL
PostgreSql: `select to_number('') from dual` throws exception ERROR: invalid input syntax for type numeric: ""

Should add check for empty string in Datum orafce_to_number(PG_FUNCTION_ARGS). Something like:
`if( !buf || !*buf )
  {
    PG_RETURN_NULL();
  }`

**Comment by okbob** [comment]
Hi

2016-09-19 9:57 GMT+02:00 dezdechado <notifications@github.com>:

> Oracle: select to_number('') from dual returns NULL
> PostgreSql: select to_number('') from dual throws exception ERROR:
> invalid input syntax for type numeric: ""
>
> Should add check for empty string in Datum orafce_to_number(PG_FUNCTION_ARGS).
> Something like:
> if( !buf || !*buf )
> {
> PG_RETURN_NULL();
> }
>

I don't try to emulate this behave - because it should not be emulated well
in all possible cases :(

PostgreSQL type "in" functions should not return NULL, so I cannot do this
conversion. So Orafce doesn't support NULL~"" behave and I don't plan it. I
am sorry. Better don't support it everywhere than support it somewhere.

You can fix it on SQL level - use own conversion function


create or replace function _(anyelement)
returns anyelement as $$
select case when $1::text = '' then NULL else $1 end;
$$ language sql;

select to_number(_('')) from ..

Regards

Pavel Stehule

**Comment by dezdechado** [comment]
Ok, thanks for explanation.
