### ISSUE TITLE
Installing orafce on PostgreSQL version 10.1

### ISSUE THREAD

**Issue by marielcherkassky** [orafce/orafce#66]
Hi,
I'm trying to upgrade my postgresql version from 9.6.3 to 10.1. I'm running the pg_upgrade check option and I get the next error : could not load library "$libdir/orafce": ERROR:  could not load library "path" undefined symbol: Float8GetDatum.

I downloaded the current source code and installed it via make install and I didnt get any errors.
Any idea how to handle it ? Does it suitable for version 10.1?

**Comment by okbob** [comment]
Had you installed Orafce for 10.1 for 64bit? Maybe you didn't use correct version of Orafce. PostgreSQL loader check the version on start, but before this step, the Linux linker check API. Orafce uses Float8GetDatum function, what is a non inlined function on 32 bit, but it is **inlined** function on 64 bit platform. So I can believe so some wrong can be there. When you compile Orafce for 10.1, then Orafce for 10.1 with your current settings was compiled, and then this issue was not possible.

**Comment by marielcherkassky** [comment]
Yes I installed it for 64bit. I solved this case but I'm not sure what was the original problem. As I mentioned I had this problem when I used pg_upgrade. So I uninstalled the extension for 9.6.3 version then installed it again and installed it on 10.1. After all this work it worked..

**Comment by okbob** [comment]
When you do upgrade, you have to have two versions Orafce, like two versions of PostgreSQL. I remember I did upgrade with pg_upgrade from 9.6 to 10.0 and it was working.
