### ISSUE TITLE
Add oracle.external_locations

### ISSUE THREAD

**Issue by sarika0607** [orafce/orafce#94]
Hi

Maybe the following view, which give similar information as oracle's external_location view, may be added to orafce.

create or replace view oracle.external_locations as
select table_name
, fdwname
, substr(opt, instr(opt, '=', -1)+1,  instr(replace(opt, '\','/'),  '/', -1)-instr(opt, '=', -1)-1 ) file_location
, substr(opt, instr(replace(opt, '\','/'), '/', -1)+1) external_file_name 
from 
(
 select relname table_name, fdwname, unnest(ftoptions) opt 
   from pg_foreign_table  
   join pg_foreign_server on (pg_foreign_table.ftserver=pg_foreign_server.oid)
   join pg_foreign_data_wrapper on (pg_foreign_server.srvfdw=pg_foreign_data_wrapper.oid) 
   join pg_class on (pg_foreign_table.ftrelid=pg_class.oid)
) as dat 
  where opt like 'filename%'

Thanks
Sarika Gupta

**Comment by okbob** [comment]
Hi, I looked to this view and your proposal, and I think so it is better to don't push it to Orafce.

These views has very low usage. Your proposal can works well only for file_fdw driver, and can be surprise if somebody will see there only file_fdw foreign tables. Isn't hard to write similar view if somebody need it. 

I don't like so this view shows only file_fdw data, but I understand so this behave is by design. So I would not to push this to orafce.

**Comment by sarika0607** [comment]
Thanks. I understand your point.

Regards
Sarika
